/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import bioportal.NCBOConfig;
import bioportal.NCBOProcessor;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.Charset;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.EqualMetricScoreCard;
import org.apache.commons.io.FileUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartPanel;
import org.json.JSONObject;
import scoring.process.BatchScoringTask;
import scoring.process.OBOElementProcess;
import static scoring.process.OBOElementProcess.SP_GENERAL_ENTITY_SIZE_LIMIT;
import static scoring.process.OBOElementProcess.SP_MAX_ELEMENT_DEPTH_LIMIT;
import static scoring.process.OBOElementProcess.SP_PROPERTY_ENTITY_LIMIT;
import static scoring.process.OBOElementProcess.SP_TOTAL_ENTITY_SIZE_LIMIT;
import scoring.process.ScoringTask;
import util.DownloadOBOLibraryTask;

/**
 *
 * @author mac
 */
public class OntokeeperUI extends javax.swing.JFrame {

    
    private ArrayList<EqualMetricScoreCard> score_cards = null;
    
    private Multimap<String, String> slices = null;
    
    ChartPanel chartPanel = null;
    
    /**
     * Creates new form OntokeeperUI
     */
    public OntokeeperUI() {
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        initComponents();
        this.setLocationRelativeTo(null);
        
        //get the slices from NCBO BioPortal
        
        slices = ArrayListMultimap.create();
        NCBOProcessor populate_slices = new   NCBOProcessor(this);
        populate_slices.initFetchForSlices();
        populate_slices.start();
        
        
        //slices = populate_slices.getSlices();
        
        
        
    }
    
    public void addSlices(Multimap<String, String> _slices){
        slices.putAll(_slices);
        this.cbSlices.removeAllItems();
        for(var s : slices.keySet()){
            System.out.println(s.toString());
            //this.cbSlices.getModel().setSelectedItem(s.toString());
            this.cbSlices.addItem(s.toString());
        }
    }

    public void setScoreCards(ArrayList<EqualMetricScoreCard> score_cards){
        this.score_cards = score_cards;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btSelectTargetOntology = new javax.swing.JButton();
        txtOntologyfile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtOutputFile = new javax.swing.JTextField();
        ckJson = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtAverageElements = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        syntacticPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        semanticPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pragmaticPanel = new javax.swing.JPanel();
        socialPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAvgElements = new javax.swing.JButton();
        btnOBOValue = new javax.swing.JButton();
        lblSemantic = new javax.swing.JLabel();
        lblSyntactic1 = new javax.swing.JLabel();
        lblOverallScore = new javax.swing.JLabel();
        lblSocial = new javax.swing.JLabel();
        lblPragmatic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnSelectBatchFolder = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtBatchFolder = new javax.swing.JTextField();
        OBOLibraryButton = new javax.swing.JButton();
        txtOBOFolder = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchTable = new javax.swing.JTable();
        exportResultsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ncboBatchTable = new javax.swing.JTable();
        btnNCBOBatchProcess = new javax.swing.JButton();
        btnNCBOExport = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btSelectTargetOntology1 = new javax.swing.JButton();
        txtOntologyfile1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtOutputFile1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNCBOApiKey = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        btnSaveNCBOAPI = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbSlices = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAddSliceOntology = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listSliceOntologies = new javax.swing.JList<>();
        btnClearSliceList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ontology file");

        btSelectTargetOntology.setText("Select File");
        btSelectTargetOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectTargetOntologyActionPerformed(evt);
            }
        });

        txtOntologyfile.setText(".....");
        txtOntologyfile.setEnabled(false);

        jLabel2.setText("Export output data");

        jButton2.setText("Output Dir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDirectoryPerformed(evt);
            }
        });

        txtOutputFile.setText(".......");
        txtOutputFile.setEnabled(false);

        ckJson.setText("JSON Format?");

        jLabel3.setText("Total Elements: ");

        txtAverageElements.setText("6,081,507");
        txtAverageElements.setToolTipText("This is based on OBO Foundry's tally taken on Oct 2025. Use the the button on the right to get an updated value if needed.");

        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        syntacticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        syntacticPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Syntactic");

        jLabel5.setText("N.B. This is determined by the library. Go to Library Scoring to derive value.");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Semantic");

        semanticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        semanticPanel.setPreferredSize(new java.awt.Dimension(4, 4));
        semanticPanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Pragmatic");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Social");

        pragmaticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pragmaticPanel.setPreferredSize(new java.awt.Dimension(179, 179));
        pragmaticPanel.setLayout(new java.awt.BorderLayout());

        socialPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        socialPanel.setEnabled(false);
        socialPanel.setPreferredSize(new java.awt.Dimension(179, 179));
        socialPanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Overall Score");

        btnAvgElements.setText("Get Element Value");
        btnAvgElements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvgElementsActionPerformed(evt);
            }
        });

        btnOBOValue.setText("Use OBO Value");
        btnOBOValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOBOValueActionPerformed(evt);
            }
        });

        lblSemantic.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSemantic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemantic.setText("0.00");

        lblSyntactic1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSyntactic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSyntactic1.setText("0.00");
        lblSyntactic1.setSize(new java.awt.Dimension(49, 17));

        lblOverallScore.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOverallScore.setText("000");

        lblSocial.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocial.setText("N/A");
        lblSocial.setSize(new java.awt.Dimension(49, 17));

        lblPragmatic.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblPragmatic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPragmatic.setText("0.00");
        lblPragmatic.setSize(new java.awt.Dimension(49, 17));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAverageElements, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvgElements)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnOBOValue, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(syntacticPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSyntactic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(semanticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemantic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pragmaticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPragmatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(socialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSelectTargetOntology)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOntologyfile, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOutputFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckJson)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblOverallScore, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelectTargetOntology)
                    .addComponent(txtOntologyfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckJson))
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAverageElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvgElements)
                    .addComponent(btnOBOValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(semanticPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(syntacticPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pragmaticPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(socialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemantic)
                    .addComponent(lblSyntactic1)
                    .addComponent(lblSocial)
                    .addComponent(lblPragmatic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOverallScore, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vanilla Scoring", jPanel2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("For the scores to be meaningful, there needs to be some benchmark to assess the overall quality of the target ontology. This panel provides a quick way to generate the metadata needed to preform the evaluation.");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setText("Folder of ontologies (ensure your own ontology is in the same folder)");

        btnSelectBatchFolder.setText("Select Folder");
        btnSelectBatchFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBatchFolderActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("OBO Foundry Library Option");

        txtBatchFolder.setEditable(false);
        txtBatchFolder.setText("....");

        OBOLibraryButton.setText("Download OBO");
        OBOLibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBOLibraryButtonActionPerformed(evt);
            }
        });

        txtOBOFolder.setEditable(false);
        txtOBOFolder.setText("...");

        jButton6.setText("Run Batch Processing");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        batchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "SYNTACTIC", "Richness", "Lawfulness", "Structure", "SEMANTIC", "Clarity", "Consitency", "Interpretability", "PRAGMATIC", "Comprehensivness", "Adaptability", "Ease of Use", "OVERALL SCORE"
            }
        ));
        batchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        batchTable.setShowGrid(true);
        jScrollPane2.setViewportView(batchTable);

        exportResultsButton.setText("Export Results");
        exportResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportResultsButtonActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("As an option you can download the resources from OBO Foundry and use the set to compare your ontology with. Please note this will take awhile to download.");
        jTextArea2.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportResultsButton)
                        .addGap(0, 686, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(OBOLibraryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOBOFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBatchFolder, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSelectBatchFolder)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OBOLibraryButton)
                    .addComponent(txtOBOFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectBatchFolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBatchFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(exportResultsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("OBO Foundry Batch Scoring", jPanel3);

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ncboBatchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "SYNTACTIC", "Richness", "Lawfulness", "Structure", "SEMANTIC", "Clarity", "Consitency", "Interpretability", "PRAGMATIC", "Comprehensivness", "Adaptability", "Ease of Use", "OVERALL SCORE"
            }
        ));
        ncboBatchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        ncboBatchTable.setShowGrid(true);
        jScrollPane4.setViewportView(ncboBatchTable);

        btnNCBOBatchProcess.setText("Run Batch Processing");
        btnNCBOBatchProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCBOBatchProcessActionPerformed(evt);
            }
        });

        btnNCBOExport.setText("Export Results");
        btnNCBOExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCBOExportActionPerformed(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("For the scores to be meaningful, there needs to be some benchmark to assess the overall quality of the target ontology. This panel provides a quick way to generate the metadata needed to preform the evaluation.");
        jTextArea3.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea3);

        jLabel10.setText("Ontology file");

        btSelectTargetOntology1.setText("Select File");
        btSelectTargetOntology1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectTargetOntologyActionPerformed(evt);
            }
        });

        txtOntologyfile1.setText(".....");
        txtOntologyfile1.setEnabled(false);

        jLabel13.setText("Export output data");

        jButton3.setText("Output Dir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDirectoryPerformed(evt);
            }
        });

        txtOutputFile1.setText(".......");
        txtOutputFile1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSelectTargetOntology1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOntologyfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNCBOBatchProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNCBOExport)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelectTargetOntology1)
                    .addComponent(txtOntologyfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtOutputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNCBOBatchProcess)
                    .addComponent(btnNCBOExport))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("NCBO BioPortal Batch Scoring", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("NCBO Bioportal Settings");

        jLabel15.setText("API Key: ");

        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("NCBO Bioportal feature requires a user api key. Visit https://bioportal.bioontology.org to attain an api key by creating a user account. Follow the instructions on how to aquire the key.");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane6.setViewportView(jTextArea4);

        btnSaveNCBOAPI.setText("Save");
        btnSaveNCBOAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNCBOAPIActionPerformed(evt);
            }
        });

        jLabel16.setText("Slice Selection or Creation:");

        jLabel17.setText("Choose a pre-existing slice from NCBO:");

        cbSlices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSlices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSlicesActionPerformed(evt);
            }
        });

        jLabel18.setText("or");

        jLabel19.setText("Create your own custom slice by adding the NCBO unique link identifier");

        btnAddSliceOntology.setText("Add");
        btnAddSliceOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSliceOntologyActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(listSliceOntologies);

        btnClearSliceList.setText("Clear");
        btnClearSliceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSliceListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNCBOApiKey, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSaveNCBOAPI))
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(cbSlices, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnAddSliceOntology)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClearSliceList)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveNCBOAPI)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(lblNCBOApiKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSlices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSliceOntology)
                    .addComponent(btnClearSliceList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Batch Scoring");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:

        System.out.println("Starting Calculation");

        //
        ScoringTask st = new ScoringTask(this);
        st.start();
        
        //Dial set up
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void outputDirectoryPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputDirectoryPerformed
        // TODO add your handling code here:
        
        FileDialog fd = new FileDialog((Frame) this, "Select file to export results");
        
        fd.setMode(FileDialog.SAVE);
        
        fd.setVisible(true);
        
        String file = fd.getFile();
        
        fd.dispose();
        
        if(!file.isEmpty()){
            this.txtOutputFile.setText(fd.getDirectory() + fd.getFile());
        }
        
        
        
    }//GEN-LAST:event_outputDirectoryPerformed

    private void btSelectTargetOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectTargetOntologyActionPerformed
        // TODO add your handling code here:

        System.out.println("Showing dialog");

        FileDialog fd = new FileDialog((Frame) this, "Select File to open");
        fd.setMode(FileDialog.LOAD);
        fd.setFile("*.owl");
        fd.setVisible(true);
        String file = fd.getFile();
        fd.dispose();
        
        if(!file.isEmpty()){
            
            System.out.println(file + " chosen.");
        
        this.txtOntologyfile.setText(fd.getDirectory() + fd.getFile());
            
        } 
        
        


    }//GEN-LAST:event_btSelectTargetOntologyActionPerformed

    private void btnSelectBatchFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBatchFolderActionPerformed
        // TODO add your handling code here:
        System.setProperty("apple.awt.fileDialogForDirectories", "true");
        FileDialog fd = new FileDialog((Frame) this, "Select directory to open");
        fd.setMode(FileDialog.LOAD);
        fd.setVisible(true);
        File selectedFile = new File(fd.getFile());
        fd.dispose();

        if (!selectedFile.getName().isEmpty()) {
            System.out.println(selectedFile.getName() + " chosen.");
            txtBatchFolder.setText(fd.getDirectory() + selectedFile.getName());
        }

        System.setProperty("apple.awt.fileDialogForDirectories", "false");


    }//GEN-LAST:event_btnSelectBatchFolderActionPerformed

    private void OBOLibraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBOLibraryButtonActionPerformed

        
        System.setProperty("apple.awt.fileDialogForDirectories", "true");
        FileDialog fd = new FileDialog((Frame) this, "Select directory to open");
        fd.setMode(FileDialog.LOAD);
        fd.setVisible(true);
        File selectedFile = new File(fd.getFile());
        fd.dispose();
        
        if (!selectedFile.getName().isEmpty()) {

            System.out.println(selectedFile.getName() + " chosen.");
            StringBuilder folder_location = new StringBuilder(fd.getDirectory() + selectedFile.getName());
            txtOBOFolder.setText(folder_location.toString());
            

            DownloadOBOLibraryTask download_task = new DownloadOBOLibraryTask(this, folder_location.toString());
            download_task.start();

        }

        System.setProperty("apple.awt.fileDialogForDirectories", "false");
        
    }//GEN-LAST:event_OBOLibraryButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed


        // TODO add your handling code here:
        
        
        System.setProperty(SP_GENERAL_ENTITY_SIZE_LIMIT, "0"); //set no limit
        System.setProperty(SP_MAX_ELEMENT_DEPTH_LIMIT, "0");
        System.setProperty(SP_PROPERTY_ENTITY_LIMIT, "0");
        System.setProperty(SP_TOTAL_ENTITY_SIZE_LIMIT, "0");
        
        
        ArrayList<EqualMetricScoreCard> score_cards = null;
        
        BatchScoringTask batch_task = new BatchScoringTask(this.txtBatchFolder.getText(), this);
        
        batch_task.start();
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void exportResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportResultsButtonActionPerformed

        //System.setProperty("apple.awt.fileDialogForDirectories", "true");
        FileDialog fd = new FileDialog((Frame) this, "Select directory to open");
        fd.setMode(FileDialog.SAVE);
        fd.setVisible(true);
        File selectedFile = new File(fd.getFile());
        fd.dispose();

        if (!selectedFile.getName().isEmpty()) {

            System.out.println(selectedFile.getName() + " chosen.");
            String file_location = fd.getDirectory() + selectedFile.getName() + ".xlsx";
            //System.setProperty("apple.awt.fileDialogForDirectories", "false");

            Thread saveThread = new Thread() {
                public void run() {

                    MessageDialog md = new MessageDialog(null, false);

                    md.setMessage("Saving. Please wait....");
                    md.setLocationRelativeTo(null);

                    try {
                        md.setVisible(true);

                        saveBatchFunction(file_location);
                    } finally {
                        md.dispose();

                        try {
                            Desktop.getDesktop().open(new File(file_location));
                        } catch (IOException ex) {
                            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                        }
                    }

                }
            };

            saveThread.start();

        }


    }//GEN-LAST:event_exportResultsButtonActionPerformed

    private void btnOBOValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOBOValueActionPerformed
        // TODO add your handling code here:
        
        OBOElementProcess obo_task = new OBOElementProcess(this);
        
        obo_task.start();
        
    }//GEN-LAST:event_btnOBOValueActionPerformed

    private void btnAvgElementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvgElementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvgElementsActionPerformed

    private void btnNCBOBatchProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCBOBatchProcessActionPerformed
        // TODO add your handling code here:
        
        //check if the API key is set
        NCBOConfig nconfig = NCBOConfig.getInstance();
        if(nconfig.getNCBOAPIKey() == null){
            
            JOptionPane.showMessageDialog(null, "You have not have API Key from NCBO Bioportal. Visit the Setting tabe for more information.", "NCBO Bioportal Warning", JOptionPane.INFORMATION_MESSAGE);
            
            return;
        }
        
        //process the user's ontology
        
        
        //process the ncbo ontologies
        
        ArrayList<EqualMetricScoreCard> score_cards = null;
        
        
    }//GEN-LAST:event_btnNCBOBatchProcessActionPerformed

    private void btnNCBOExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCBOExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNCBOExportActionPerformed

    private void btnSaveNCBOAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNCBOAPIActionPerformed
        // TODO add your handling code here:
        
        
        String api_value = this.lblNCBOApiKey.getText();
        
        if(api_value.isBlank() || api_value.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please populate the field with your NCBO BioPortal API Key.", "Settings Warning", JOptionPane.INFORMATION_MESSAGE);
            
            return;
        
        }
        NCBOConfig nconfig = NCBOConfig.getInstance();
        boolean is_successful = nconfig.setNCBOAPIKey(api_value);
        
        if(is_successful){
            JOptionPane.showMessageDialog(null, "Your API Key has been saved. You can now use the NCBO BioPortal feature.", "Settings Message", JOptionPane.INFORMATION_MESSAGE);
        }
        

        
    }//GEN-LAST:event_btnSaveNCBOAPIActionPerformed

    private void cbSlicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSlicesActionPerformed
        // TODO add your handling code here:
        
        if(this.cbSlices.getSelectedIndex()>-1){
            String selection = (String)cbSlices.getSelectedItem();
            
            Collection<String> slice_ontologies = this.slices.get(selection);
            
            DefaultListModel list_ontologies = new DefaultListModel();
            for(var so : slice_ontologies){
                list_ontologies.addElement(so.toString());
            }
            this.listSliceOntologies.setModel(list_ontologies);
            
        }
        
    }//GEN-LAST:event_cbSlicesActionPerformed

    private void btnClearSliceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSliceListActionPerformed
        // TODO add your handling code here:
        
        //DefaultListModel list_ontologies = new Default
        DefaultListModel listModel =(DefaultListModel)listSliceOntologies.getModel();
        listModel.removeAllElements();
    }//GEN-LAST:event_btnClearSliceListActionPerformed

    private void btnAddSliceOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSliceOntologyActionPerformed
        // TODO add your handling code here:
        AddNCBOOntologyDialog d = new AddNCBOOntologyDialog(this, true);
        d.setVisible(true);
        
    }//GEN-LAST:event_btnAddSliceOntologyActionPerformed

    public void setElementValue(long value){
        
        this.txtAverageElements.setText(String.valueOf(value));
        
    }
    
    public long getElementValue(){
        
        System.out.println(txtAverageElements.getText().replaceAll(",", ""));
        
        Long value = Long.parseLong(txtAverageElements.getText().replaceAll(",", "") );
        
        return value;
        
    }
    
    public String getTxtOntologyFile(){
        
        if(this.txtOntologyfile.getText().isEmpty()){
            
            return null;
            
        }
        
        return txtOntologyfile.getText();
        
    }
    
    public void setScoresForOntology(EqualMetricScoreCard score_card){
        
        
        
        //setDial Socres
        setUIScorePanel(score_card);
        //save scores
        exportScoresForOntology(score_card);
        
        
        
    }
    
    public void exportScoresForOntology(EqualMetricScoreCard score_card){
        
        
        
        try {
            if(!txtOutputFile.getText().isBlank()){
                
                String output = txtOutputFile.getText() + ".txt";
                
                if(ckJson.isSelected()){
                    
                    
                    FileUtils.writeStringToFile(new File(txtOutputFile.getText().concat(".json")), score_card.toJson().toString(), Charset.forName("UTF-8"));
                }
                else{
                    FileUtils.writeStringToFile(new File(output), score_card.toString(), Charset.forName("UTF-8"));
                }
                
                
            }
            
            
        } catch (IOException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    
    public void setUIScorePanel(EqualMetricScoreCard score_card){
        
        
        DecimalFormat df = new DecimalFormat("#.###");
        
        double syntactic =  score_card.getSyntacticScore();
        double semantic = score_card.getSemanticScore();
        double pragmatic = score_card.getPragmaticScore();
        double social = 0.00;
        double overall = score_card.getOverallScore();
        
        syntacticPanel.removeAll();
        semanticPanel.removeAll();
        pragmaticPanel.removeAll();
        socialPanel.removeAll();

        ChartPanel syntactic_dial = ScoreDial.getInstance().generateScoreDial(syntactic, 178, 178);
        
        syntacticPanel.add(syntactic_dial, BorderLayout.CENTER);
        
        ChartPanel semantic_dial = ScoreDial.getInstance().generateScoreDial(semantic, 178, 178);
        
        semanticPanel.add(semantic_dial, BorderLayout.CENTER);
        
        pragmaticPanel.add(ScoreDial.getInstance().generateScoreDial(pragmatic, 178, 178), BorderLayout.CENTER);
        
        socialPanel.add(ScoreDial.getInstance().generateScoreDial(social, 178, 178), BorderLayout.CENTER);
        
        socialPanel.setEnabled(false);
        
        this.lblOverallScore.setText(df.format(overall));
        
        this.lblSyntactic1.setText(df.format(syntactic));
        this.lblSemantic.setText(df.format(semantic));
        this.lblPragmatic.setText(df.format(pragmatic));
        
    }
    
    private void saveBatchFunction(String folder_location){
        XSSFWorkbook workbook = new XSSFWorkbook();
        
        Sheet sheet = workbook.createSheet("Results");
        
        
        //create header
        
        Row header = sheet.createRow(0);
        CellStyle header_style = workbook.createCellStyle();
        XSSFFont bold_font = ((XSSFWorkbook) workbook).createFont();
        bold_font.setBold(true);
        header_style.setFont(bold_font);
        
        Cell cell = header.createCell(0);
        cell.setCellValue("ONTOLOGY");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(1);
        cell.setCellValue("SYNTACTIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(2);
        cell.setCellValue("Richness");
        cell.setCellStyle(header_style);
        
        
        cell = header.createCell(3);
        cell.setCellValue("Lawfulness");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(4);
        cell.setCellValue("Structure");
        cell.setCellStyle(header_style);
        
        
        cell = header.createCell(5);
        cell.setCellValue("SEMANTIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(6);
        cell.setCellValue("Clarity");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(7);
        cell.setCellValue("Consistency");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(8);
        cell.setCellValue("Interpertability");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(9);
        cell.setCellValue("PRAGMATIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(10);
        cell.setCellValue("Comprehensiveness");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(11);
        cell.setCellValue("Adaptibility");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(12);
        cell.setCellValue("Ease of Use");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(13);
        cell.setCellValue("OVERALL SCORE");
        cell.setCellStyle(header_style);
        
        TableModel table_model = batchTable.getModel();
        
        int rowCount = table_model.getRowCount();
        int columnCount = table_model.getColumnCount();
        
        for(int x=0; x < rowCount; x++){
            
            Row createRow = sheet.createRow(x+1);
            
            for(int y=0; y < columnCount; y++){
                
                Object value = table_model.getValueAt(x, y);
                cell = createRow.createCell(y);
                
                if(value instanceof Double){
                    cell.setCellValue((double)value);
                }
                else{
                    cell.setCellValue((String)value);
                }
                
                
            }
            
        }
        
        
        
        
        try {
            
            FileOutputStream outputStream = new FileOutputStream(folder_location);
            workbook.write(outputStream);
            
            
            workbook.close();
            
        } catch (FileNotFoundException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            
            
            UIManager.setLookAndFeel( new FlatLightLaf() );
            
            
            
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(OntokeeperUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            

        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OntokeeperUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OBOLibraryButton;
    private javax.swing.JTable batchTable;
    private javax.swing.JButton btSelectTargetOntology;
    private javax.swing.JButton btSelectTargetOntology1;
    private javax.swing.JButton btnAddSliceOntology;
    private javax.swing.JButton btnAvgElements;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClearSliceList;
    private javax.swing.JButton btnNCBOBatchProcess;
    private javax.swing.JButton btnNCBOExport;
    private javax.swing.JButton btnOBOValue;
    private javax.swing.JButton btnSaveNCBOAPI;
    private javax.swing.JButton btnSelectBatchFolder;
    private javax.swing.JComboBox<String> cbSlices;
    private javax.swing.JCheckBox ckJson;
    private javax.swing.JButton exportResultsButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField lblNCBOApiKey;
    private javax.swing.JLabel lblOverallScore;
    private javax.swing.JLabel lblPragmatic;
    private javax.swing.JLabel lblSemantic;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblSyntactic1;
    private javax.swing.JList<String> listSliceOntologies;
    private javax.swing.JTable ncboBatchTable;
    private javax.swing.JPanel pragmaticPanel;
    private javax.swing.JPanel semanticPanel;
    private javax.swing.JPanel socialPanel;
    private javax.swing.JPanel syntacticPanel;
    private javax.swing.JTextField txtAverageElements;
    private javax.swing.JTextField txtBatchFolder;
    private javax.swing.JTextField txtOBOFolder;
    private javax.swing.JTextField txtOntologyfile;
    private javax.swing.JTextField txtOntologyfile1;
    private javax.swing.JTextField txtOutputFile;
    private javax.swing.JTextField txtOutputFile1;
    // End of variables declaration//GEN-END:variables

    public void populateScoreTable() {
        
        
        batchTable.removeAll();
        
        DefaultTableModel model = (DefaultTableModel) batchTable.getModel();
        
        score_cards.forEach(card->{
            
            
            Object[] o = new Object[14];
            o[0] = card.getOntologyId();
            
            o[1] = card.getSyntacticScore();
            o[2] = card.getRichnessScore();
            o[3] = card.getLawfulnessScore();
            o[4] = card.getStructureScore();
            
            o[5] = card.getSemanticScore();
            o[6] = card.getClarityScore();
            o[7] = card.getConsistencyScore();
            o[8] = card.getInterpertabilityScore();
            
            o[9] = card.getPragmaticScore();
            o[10] = card.getComprehensivenessCore();
            o[11] = card.getAdaptabilityScore();
            o[12] = card.getEaseOfUseScore();
            
            o[13] = card.getOverallScore();
            
        
            
            model.addRow(o);
            
        });
        
       
        
    }

    void insertNCBOOntology(String ncbo_id) {
        DefaultListModel model = (DefaultListModel)this.listSliceOntologies.getModel();
        //model.addRow(ncbo_id);
        model.addElement(ncbo_id);
        
    }
}
