/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.Charset;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.EqualMetricScoreCard;
import org.apache.commons.io.FileUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jfree.chart.ChartPanel;
import org.json.JSONObject;
import scoring.process.BatchScoringTask;
import scoring.process.OBOElementProcess;
import scoring.process.ScoringTask;

/**
 *
 * @author mac
 */
public class OntokeeperUI extends javax.swing.JFrame {

    
    private ArrayList<EqualMetricScoreCard> score_cards = null;
    
    ChartPanel chartPanel = null;
    
    /**
     * Creates new form OntokeeperUI
     */
    public OntokeeperUI() {
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    

    public void setScoreCards(ArrayList<EqualMetricScoreCard> score_cards){
        this.score_cards = score_cards;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btSelectTargetOntology = new javax.swing.JButton();
        txtOntologyfile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtOutputFile = new javax.swing.JTextField();
        ckJson = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtAverageElements = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        syntacticPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        semanticPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pragmaticPanel = new javax.swing.JPanel();
        socialPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAvgElements = new javax.swing.JButton();
        btnOBOValue = new javax.swing.JButton();
        lblSemantic = new javax.swing.JLabel();
        lblSyntactic1 = new javax.swing.JLabel();
        lblOverallScore = new javax.swing.JLabel();
        lblSocial = new javax.swing.JLabel();
        lblPragmatic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        btnSelectBatchFolder = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtBatchFolder = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txtBatchOutputFolder = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchTable = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ontology file");

        btSelectTargetOntology.setText("Select File");
        btSelectTargetOntology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectTargetOntologyActionPerformed(evt);
            }
        });

        txtOntologyfile.setText(".....");
        txtOntologyfile.setEnabled(false);

        jLabel2.setText("Export output data");

        jButton2.setText("Output Dir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtOutputFile.setText(".......");
        txtOutputFile.setEnabled(false);

        ckJson.setText("JSON Format?");

        jLabel3.setText("Total Elements: ");

        txtAverageElements.setText("6,081,507");
        txtAverageElements.setToolTipText("This is based on OBO Foundry's tally taken on Oct 2025. Use the the button on the right to get an updated value if needed.");

        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        syntacticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        syntacticPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Syntactic");

        jLabel5.setText("N.B. This is determined by the library. Go to Library Scoring to derive value.");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Semantic");

        semanticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        semanticPanel.setPreferredSize(new java.awt.Dimension(4, 4));
        semanticPanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Pragmatic");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Social");

        pragmaticPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pragmaticPanel.setPreferredSize(new java.awt.Dimension(179, 179));
        pragmaticPanel.setLayout(new java.awt.BorderLayout());

        socialPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        socialPanel.setEnabled(false);
        socialPanel.setPreferredSize(new java.awt.Dimension(179, 179));
        socialPanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Overall Score");

        btnAvgElements.setText("Get Element Value");

        btnOBOValue.setText("Use OBO Value");
        btnOBOValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOBOValueActionPerformed(evt);
            }
        });

        lblSemantic.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSemantic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemantic.setText("0.00");

        lblSyntactic1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSyntactic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSyntactic1.setText("0.00");
        lblSyntactic1.setSize(new java.awt.Dimension(49, 17));

        lblOverallScore.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOverallScore.setText("000");

        lblSocial.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSocial.setText("N/A");
        lblSocial.setSize(new java.awt.Dimension(49, 17));

        lblPragmatic.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblPragmatic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPragmatic.setText("0.00");
        lblPragmatic.setSize(new java.awt.Dimension(49, 17));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAverageElements, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvgElements)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnOBOValue, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(syntacticPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSyntactic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(semanticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemantic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pragmaticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPragmatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(socialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSelectTargetOntology)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOntologyfile, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOutputFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckJson)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblOverallScore, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelectTargetOntology)
                    .addComponent(txtOntologyfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckJson))
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAverageElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvgElements)
                    .addComponent(btnOBOValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semanticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(syntacticPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socialPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pragmaticPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemantic)
                    .addComponent(lblSyntactic1)
                    .addComponent(lblSocial)
                    .addComponent(lblPragmatic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOverallScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vanilla Scoring", jPanel2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("For the scores to be meaningful, there needs to be some benchmark to assess the overall quality of the target ontology. This panel provides a quick way to generate the metadata needed to preform the evaluation.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setText("Folder of ontologies");

        btnSelectBatchFolder.setText("Select Folder");
        btnSelectBatchFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBatchFolderActionPerformed(evt);
            }
        });

        jLabel12.setText("Output folder of results");

        txtBatchFolder.setEditable(false);
        txtBatchFolder.setText("....");

        jButton5.setText("Output Dir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtBatchOutputFolder.setEditable(false);
        txtBatchOutputFolder.setText("...");

        jButton6.setText("Run Batch Processing");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        batchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "SYNTACTIC", "Richness", "Lawfulness", "SEMANTIC", "Clarity", "Consitency", "Interpretability", "PRAGMATIC", "Comprehensivness", "OVERALL SCORE"
            }
        ));
        batchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        batchTable.setShowGrid(true);
        jScrollPane2.setViewportView(batchTable);

        jButton7.setText("Export Results");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSelectBatchFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBatchFolder))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBatchOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectBatchFolder)
                    .addComponent(txtBatchFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(txtBatchOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Batch Scoring", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Batch Scoring");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:

        System.out.println("Starting Calculation");

        //
        ScoringTask st = new ScoringTask(this);
        st.start();
        
        //Dial set up
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        FileDialog fd = new FileDialog((Frame) this, "Select file to export results");
        
        fd.setMode(FileDialog.SAVE);
        
        fd.setVisible(true);
        
        String file = fd.getFile();
        
        fd.dispose();
        
        this.txtOutputFile.setText(fd.getDirectory() + fd.getFile());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btSelectTargetOntologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectTargetOntologyActionPerformed
        // TODO add your handling code here:

        System.out.println("Showing dialog");

        FileDialog fd = new FileDialog((Frame) this, "Select File to open");
        fd.setMode(FileDialog.LOAD);
        fd.setFile("*.owl");
        fd.setVisible(true);
        String file = fd.getFile();
        fd.dispose();
        System.out.println(file + " chosen.");
        
        this.txtOntologyfile.setText(fd.getDirectory() + fd.getFile());


    }//GEN-LAST:event_btSelectTargetOntologyActionPerformed

    private void btnSelectBatchFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBatchFolderActionPerformed
        // TODO add your handling code here:
        System.setProperty("apple.awt.fileDialogForDirectories", "true");
        FileDialog fd = new FileDialog((Frame) this, "Select directory to open");
        fd.setMode(FileDialog.LOAD);
        fd.setVisible(true);
        File selectedFile = new File(fd.getFile());
        fd.dispose();
        System.out.println(selectedFile.getName() + " chosen.");
        txtBatchFolder.setText(fd.getDirectory() + selectedFile.getName());
        System.setProperty("apple.awt.fileDialogForDirectories", "false");

        
    }//GEN-LAST:event_btnSelectBatchFolderActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //System.setProperty("apple.awt.fileDialogForDirectories", "true");
        FileDialog fd = new FileDialog((Frame) this, "Select directory to open");
        fd.setMode(FileDialog.SAVE);
        fd.setVisible(true);
        File selectedFile = new File(fd.getFile());
        fd.dispose();
        System.out.println(selectedFile.getName() + " chosen.");
        txtBatchOutputFolder.setText(fd.getDirectory() + selectedFile.getName()+ ".xlsx");
        //System.setProperty("apple.awt.fileDialogForDirectories", "false");
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<EqualMetricScoreCard> score_cards = null;
        
        BatchScoringTask batch_task = new BatchScoringTask(this.txtBatchFolder.getText(), this);
        
        batch_task.start();
        
  
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
   
        
        Thread saveThread = new Thread(){
            public void run(){
                
                MessageDialog md = new MessageDialog(null, false);
                
                md.setMessage("Saving. Please wait....");
                md.setLocationRelativeTo(null);
                
                try{
                    md.setVisible(true);
                    
                    saveBatchFunction();
                }
                
                finally{
                    md.dispose();
                    
                    try {
                        Desktop.getDesktop().open(new File(txtBatchOutputFolder.getText()));
                    } catch (IOException ex) {
                        System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
                
                
                
            }
        };
        
        saveThread.start();
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnOBOValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOBOValueActionPerformed
        // TODO add your handling code here:
        
        OBOElementProcess obo_task = new OBOElementProcess(this);
        
        obo_task.start();
        
    }//GEN-LAST:event_btnOBOValueActionPerformed

    public void setElementValue(long value){
        
        this.txtAverageElements.setText(String.valueOf(value));
        
    }
    
    public long getElementValue(){
        
        System.out.println(txtAverageElements.getText().replaceAll(",", ""));
        
        Long value = Long.parseLong(txtAverageElements.getText().replaceAll(",", "") );
        
        return value;
        
    }
    
    public String getTxtOntologyFile(){
        
        if(this.txtOntologyfile.getText().isEmpty()){
            
            return null;
            
        }
        
        return txtOntologyfile.getText();
        
    }
    
    public void setScoresForOntology(EqualMetricScoreCard score_card){
        
        
        
        //setDial Socres
        setUIScorePanel(score_card);
        //save scores
        exportScoresForOntology(score_card);
        
        
        
    }
    
    public void exportScoresForOntology(EqualMetricScoreCard score_card){
        
        
        
        try {
            if(!txtOutputFile.getText().isBlank()){
                
                String output = txtOutputFile.getText() + ".txt";
                
                if(ckJson.isSelected()){
                    
                    
                    FileUtils.writeStringToFile(new File(txtOutputFile.getText().concat(".json")), score_card.toJson().toString(), Charset.forName("UTF-8"));
                }
                else{
                    FileUtils.writeStringToFile(new File(output), score_card.toString(), Charset.forName("UTF-8"));
                }
                
                
            }
            
            
        } catch (IOException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    
    public void setUIScorePanel(EqualMetricScoreCard score_card){
        
        
        DecimalFormat df = new DecimalFormat("#.###");
        
        double syntactic =  score_card.getSyntacticScore();
        double semantic = score_card.getSemanticScore();
        double pragmatic = score_card.getPragmaticScore();
        double social = 0.00;
        double overall = score_card.getOverallScore();
        
        syntacticPanel.removeAll();
        semanticPanel.removeAll();
        pragmaticPanel.removeAll();
        socialPanel.removeAll();

        ChartPanel syntactic_dial = ScoreDial.getInstance().generateScoreDial(syntactic, 178, 178);
        
        syntacticPanel.add(syntactic_dial, BorderLayout.CENTER);
        
        ChartPanel semantic_dial = ScoreDial.getInstance().generateScoreDial(semantic, 178, 178);
        
        semanticPanel.add(semantic_dial, BorderLayout.CENTER);
        
        pragmaticPanel.add(ScoreDial.getInstance().generateScoreDial(pragmatic, 178, 178), BorderLayout.CENTER);
        
        socialPanel.add(ScoreDial.getInstance().generateScoreDial(social, 178, 178), BorderLayout.CENTER);
        
        socialPanel.setEnabled(false);
        
        this.lblOverallScore.setText(df.format(overall));
        
        this.lblSyntactic1.setText(df.format(syntactic));
        this.lblSemantic.setText(df.format(semantic));
        this.lblPragmatic.setText(df.format(pragmatic));
        
    }
    
    private void saveBatchFunction(){
        XSSFWorkbook workbook = new XSSFWorkbook();
        
        Sheet sheet = workbook.createSheet("Results");
        
        
        //create header
        
        Row header = sheet.createRow(0);
        CellStyle header_style = workbook.createCellStyle();
        XSSFFont bold_font = ((XSSFWorkbook) workbook).createFont();
        bold_font.setBold(true);
        header_style.setFont(bold_font);
        
        Cell cell = header.createCell(0);
        cell.setCellValue("ONTOLOGY");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(1);
        cell.setCellValue("SYNTACTIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(2);
        cell.setCellValue("Richness");
        cell.setCellStyle(header_style);
        
        
        cell = header.createCell(3);
        cell.setCellValue("Lawfulness");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(4);
        cell.setCellValue("SEMANTIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(5);
        cell.setCellValue("Clarity");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(6);
        cell.setCellValue("Consistency");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(7);
        cell.setCellValue("Interpertability");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(8);
        cell.setCellValue("PRAGMATIC");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(9);
        cell.setCellValue("Comprehensiveness");
        cell.setCellStyle(header_style);
        
        cell = header.createCell(10);
        cell.setCellValue("OVERALL SCORE");
        cell.setCellStyle(header_style);
        
        TableModel table_model = batchTable.getModel();
        
        int rowCount = table_model.getRowCount();
        int columnCount = table_model.getColumnCount();
        
        for(int x=0; x < rowCount; x++){
            
            Row createRow = sheet.createRow(x+1);
            
            for(int y=0; y < columnCount; y++){
                
                Object value = table_model.getValueAt(x, y);
                cell = createRow.createCell(y);
                
                if(value instanceof Double){
                    cell.setCellValue((double)value);
                }
                else{
                    cell.setCellValue((String)value);
                }
                
                
            }
            
        }
        
        
        
        
        try {
            
            FileOutputStream outputStream = new FileOutputStream(this.txtBatchOutputFolder.getText());
            workbook.write(outputStream);
            
            
            workbook.close();
            
        } catch (FileNotFoundException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(OntokeeperUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            
            
            UIManager.setLookAndFeel( new FlatLightLaf() );
            
            
            
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(OntokeeperUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            

        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OntokeeperUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable batchTable;
    private javax.swing.JButton btSelectTargetOntology;
    private javax.swing.JButton btnAvgElements;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnOBOValue;
    private javax.swing.JButton btnSelectBatchFolder;
    private javax.swing.JCheckBox ckJson;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblOverallScore;
    private javax.swing.JLabel lblPragmatic;
    private javax.swing.JLabel lblSemantic;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblSyntactic1;
    private javax.swing.JPanel pragmaticPanel;
    private javax.swing.JPanel semanticPanel;
    private javax.swing.JPanel socialPanel;
    private javax.swing.JPanel syntacticPanel;
    private javax.swing.JTextField txtAverageElements;
    private javax.swing.JTextField txtBatchFolder;
    private javax.swing.JTextField txtBatchOutputFolder;
    private javax.swing.JTextField txtOntologyfile;
    private javax.swing.JTextField txtOutputFile;
    // End of variables declaration//GEN-END:variables

    public void populateScoreTable() {
        
        
        batchTable.removeAll();
        
        DefaultTableModel model = (DefaultTableModel) batchTable.getModel();
        
        score_cards.forEach(card->{
            
            
            Object[] o = new Object[11];
            o[0] = card.getOntologyId();
            o[1] = card.getSyntacticScore();
            o[2] = card.getRichnessScore();
            o[3] = card.getLawfulnessScore();
            o[4] = card.getSemanticScore();
            o[5] = card.getClarityScore();
            o[6] = card.getConsistencyScore();
            o[7] = card.getInterpertabilityScore();
            o[8] = card.getPragmaticScore();
            o[9] = card.getPragmaticScore();
            o[10] = card.getOverallScore();
            
        
            
            model.addRow(o);
            
        });
        
       
        
    }
}
